//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEvaluations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<double> YR_OF_SVC { get; set; }
        public Nullable<System.DateTime> UNIV_START_DATE { get; set; }
        public Nullable<System.DateTime> LIBRARY_START_DATE { get; set; }
        public string UIN { get; set; }
        public string NETID { get; set; }
        public string NETID_DOMAIN { get; set; }
        public string RACE_ALT { get; set; }
        public Nullable<System.DateTime> BIRTH_DT { get; set; }
        public string GENDER { get; set; }
        public string ECLASS { get; set; }
    }
}
