//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEvaluations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDList
    {
        public int id { get; set; }
        public string empNetId { get; set; }
        public string supNetId { get; set; }
        public string JDname { get; set; }
        public string JDSuper { get; set; }
        public Nullable<int> jdid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
    }
}
