//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEvaluations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDescription
    {
        public int jdid { get; set; }
        public string netid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public string posnNumber { get; set; }
    }
}
