//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEvaluations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportingLine
    {
        public int id { get; set; }
        public string empNetId { get; set; }
        public string supNetId { get; set; }
        public string empFirst { get; set; }
        public string empLast { get; set; }
        public string empName { get; set; }
        public string supFirst { get; set; }
        public string supLast { get; set; }
        public string supName { get; set; }
    }
}
